export default {
	Header: {
		en: {
			title: "Anna Branco's professional profile",
			contact: 'Contact me'
		},
		es: {
			title: "Perfil profesional de Anna Branco",
			contact: 'Contactarme'
		},
		pt: {
			title: "Perfil profissional de Anna Branco",
			contact: 'Me contatar'
		},
	},
	 Hero: {
		 en: {
			 job: 'Front end junior developer',
			 aditional: 'Learning to develop sites where navigating around is a beautiful journey',
			 call: 'Call',
			 chat: 'Chat',
			 thankyou: 'Thank you very much for navigating trough all my profile!'
		 },
		 es: {
			 job: 'Desarrolladora Front end junior',
			 aditional: 'Aprendiendo a desarrollar sitios por donde navegar sea un bonita experiencia',
			 call: 'Llamar',
			 chat: 'Mensaje',
			 thankyou: 'Muchas gracias por nevegar por todo mi perfil!'
		 },
		 pt: {
			 job: 'Programadora Front end júnior',
			 aditional: 'Aprendendo a desenvolver sites pelos quais navegar seja uma bonita experiência',
			 call: 'Chamar',
			 chat: 'Chat',
			 thankyou: 'Muito obrigada por navegar por todo o meu perfil!'
		 }
	},
	Developer: {
		en: {
			title: 'Technical competences',
			main: 'Main skills',
			other: 'Other skills',
			formation: 'Formation by',
			more: 'Know more',
			expanded: 'Expanded view',
			reduced: 'Reduced view',
			projects: 'Projects',
			adalabText: 'Adalab is an intensive formation program aiming the inclusion of women on the technology sector. In four months, with an average of 9 daily hours of studies (6 of them presential), we dive in deeply on the technical aspects of front-end and learn important skills for professional development. We also work with agile methodologies.',
			adalabMore: 'To know more about Adalab, you may visit their website: ',
			projectsText: 'In this section, you can see a few of my projects and creations:',
			showThumbnails: 'Show thumbnails',
			goUp: 'go up',
			showMore: 'show more',
		},
		es: {
			title: 'Competencias técnicas',
			main: 'Principales habilidades',
			other: 'Otras habilidades',
			formation: 'Formación por',
			more: 'Sepa más',
			expanded: 'Expandir visualización',
			reduced: 'Reducir visualización',
			projects: 'Proyectos',
			adalabText: 'Adalab es un programa de formación intensiva destinado a la inclusión de mujeres en el sector tecnológico. En cuatro meses, con una media de 9 horas de estudios por día (6 presenciales), nos profundizamos en la parte técnica de front-end, bien como importantes temas de desarrollo profesional. Trabajamos también com metodologías ágiles.',
			adalabMore: 'Para saber más informaciones sobre Adalab, puedes consultar su página web: ',
			projectsText: 'En esta sección puede ver algunos de mis proyectos y creacciones:',
			showThumbnails: 'Enseñar miniaturas',
			goUp: 'subir',
			showMore: 'ver más',
		},
		pt: {
			title: 'Competências técnicas',
			main: 'Principais habilidades',
			other: 'Outras habilidades',
			formation: 'Formação por',
			more: 'Saiba mais',
			expanded: 'Expandir visualização',
			reduced: 'Reduzir visualização',
			projects: 'Projetos',
			adalabText: 'Adalab é um programa de formação intensiva destinado à inclusão de mulheres no setor tecnológico. Em quatro meses, com uma média de 9 horas diárias de estudos (6 das quais presenciais), nos aprofundamos na parte técnica de front-end e também em importantes temas relacionados ao desenvolvimento profissional. Trabalhamos também com metologias ágeis.',
			adalabMore: 'Para saber mais informações sobre Adalab, você pode consultar sua página web: ',
			projectsText: 'Nesta seção você pode ser alguns de meus projetos e criações:',
			showThumbnails: 'Mostrar miniaturas',
			goUp: 'subir',
			showMore: 'ver mais',
		}
   	},
   	Formation: {
		en: {
			title: 'Formation',
			psy: 'Psychology',
			ir: 'International Relations',
			master: 'Master in International Relations',
			grade: 'Final grade: ',
			brazil: 'Brazil',
			spain: 'Spain'
	   	},
	   	es: {
			title: 'Formación',
			psy: 'Psicología',
			ir: 'Relaciones Internacionales',
			master: 'Master en Relaciones Internacionales',
			grade: 'Grado final: ',
			brazil: 'Brasil',
			spain: 'España'
	   	},
	   	pt: {
			title: 'Formação',
			psy: 'Psicologia',
			ir: 'Relações Internacionais',
			master: 'Mestrado em Relações Internacionais',
			grade: 'Média final: ',
			brazil: 'Brasil',
			spain: 'Espanha'
	   	}
	},
	Seabed: {
		en: {
			title: 'Other informations',
			message: 'Beyond developing webpages and applications, I love to experiment programming videogames, promoting interactivity with the user and lots of fun.',
			messageKeyboard: 'Thus, now you know my basic profile, how about a little gaming experience? Move the diver to the desired direction using arrows keys right or left on your keyboard (◀︎ or ▶︎) to know more about my profile.',
			messageDevices: 'Thus, now you know my basic profile, how about a little gaming experience? If you want more information about previous experiences or other skills, move the scuba diver to the desired direction clicking the directional keys right or left on the corners of the screen.',
			experiences: 'Previous experiences',
			skills: 'Other skills',
			time2go: 'Time to go back...',
			click2close: 'Click HERE to close this window',
			thoughts: [
				'Yeah. I too would love to explore around, but we have to focus on the professional profile, right?',
				"That's weird... I could swear I've just seen a cat dressed up as an octopus",
				'The sea... the final frontier...',
				'hmm... maybe another day.',
				"I've just remembered that old movie with an alien ship living on an underwater abyss...",
				'Just keep swimming... Just keep swiiimming...',
				'Sometimes I forget I am just a character inside a professional profile',
				'Oh.. I wish we had time to swimm around...'
			]
		},
		es: {
			title: 'Otras informaciones',
			message: 'Además de desarrollar páginas y aplicaciones, me encanta experimentar con la programación de videojuegos, promoviendo interactividad con el usuario de una manera bastante lúdica.',
			messageKeyboard: 'Pues, ahora que Usted ya conoce mi perfil básico, qué le parece jugar un poco? Mueve la buceadora para la dirección deseada usando las flechas para la derecha o izquierda del teclado (◀︎ o ▶︎) para saber más sobre mi perfil.',
			messageDevices: 'Pues, ahora que Usted ya conoce mi perfil básico, qué le parece jugar un poco? Si quiere saber más informaciones acerca de mis experiencias anteriores u otras habilidades, mueve la buceadora para la dirección deseada haciendo click en las flechas direccionales en los cantos de la pantalla para la derecha o izquierda.',
			experiences: 'Experiencias anteriores',
			skills: 'Otras habilidades',
			time2go: 'Es hora de volver...',
			click2close: 'Haz click AQUÍ para cerrar esta ventana',
			thoughts: [
				'Ya... a mí también me encantaría explorar más, pero tenemos que focarnos en el perfil profesional, ¿verdad?',
				'Que raro... podría jurar que he visto un gato disfrazado de pulpo',
				'El mar... la frontera final...',
					'hmm... quizás otro día',
				'Me acordé ahora de aquella peli antigua con una nave alienígena viviendo en un abismo en el mar...',
				'Nadaremos, nadaremos... en el maaar...',
				'Hay veces que se me olvida que soy solo una personaje dentro de un perfil profesional',
				'Oh.. me gustaría que tuviesemos tiempo para nadar por allí...'
			]
		},
		pt: {
			title: 'Outras informações',
			message: 'Além de desenvolver páginas e aplicacões, adoro experimentar com programação de jogos, promovendo interatividade com o usuário de uma maneira bastante lúdica.',
			messageKeyboard: 'Assim, agora que você já conhece meu perfil básico, que tal jogar um pouco? Mova a mergulhadora para a direção desejada usando as setas para direita ou esquerda do teclado (◀︎ ou ▶︎) para saber mais sobre o meu perfil.',
			messageDevices: 'Assim, agora que você já conhece meu perfil básico, que tal jogar um pouco? Se você quiser saber mais informações sobre minhas experiências anteriores ou outras habilidades, mova a mergulhadora para a direção desejada clicando nas setas direcionais nos cantos da tela para direita ou esquerda.',
			experiences: 'Experiências anteriores',
			skills: 'Outras habilidades',
			time2go: 'É hora de voltar...',
			click2close: 'Clique AQUI para fechar essa janela',
			thoughts: [
				'Pois é... eu também adoraria explorar mais, mas temos que nos focar no perfil profissional, não é?',
				'Que estranho... eu poderia jurar que acabei de ver um gato disfarçado de polvo',
				'O mar... a fronteira final...',
				'hmm... talvez outro dia',
				'Me lembrei agora daquele filme antigo com uma nave alienígena vivendo em um abismo no mar...',
				'Continue a nadar... continue a nadaaar...',
				'Às vezes eu esqueço que sou só uma personagem dentro de um perfil profissional',
				'Oh.. eu gostaria que tivéssemos tempo para nadar por aí...'
			]
		}
 	},
	Experiences: {
		en: {
			find: "You've found a curious object laying on the sea bed.",
			investigate: 'Click on in to investigate it.',
			ict: 'ICT Instructor',
			ictDetails: 'I gave classes on Information and Communication Technology skills: windows environment, basic software use and internet. Teaching more than 210 kids of Primary Education, from 6 up to 12 years old.',
			eru: 'International Emergencies Response Delegate (ERU)',
			eruDetails: 'I was deployed in Greece on a temporary mission (2 months), providing psychosocial support for Syrian people and other refugees arriving in Europe.',
			tj: 'Public Servant',
			tjDetails: 'Public servant with a rising carreer beginning as administrative technician coming to head of sector responsible for social projects.',
			linkedin: 'For more details ans references, please visit ',
			brazil: 'Brazil',
			spain: 'Spain'
		},
		es: {
			find: 'Has encontrado un objecto curioso en el fondo del mar.',
			investigate: 'Haz click en ello para investigarlo.',
			ict: 'Instructora de TIC',
			ictDetails: 'He impartido clases sobre habilidades de Tecnología de la Información y Comunicación: ambiente windows, aplicaciones básicas y uso de internet, enseñando más de 210 niños y niñas de Educación Primaria, de los 6 a los 12 años de edad.',
			eru: 'Delegada Internacional de Respuesta en Emergencias (ERU)',
			eruDetails: 'he sido desplegada a Grecia un misión temporal (2 meses), brindando apoyo psicosocial a personas sirias y otros refugiados y refugiadas llegando a Europa.',
			tj: 'Funcionaria Pública',
			tjDetails: 'Funcionaria con carrera ascendente, empezando como técnica administrativa y llegando a ser jefe de sector responsable por proyectos sociales.',
			linkedin: 'Para más detalles y referencias, por favor visite ',
			brazil: 'Brasil',
			spain: 'España'
		},
		pt: {
			find: 'Você encontrou um objeto curioso no fundo do mar.',
			investigate: 'Clique nele para investigá-lo.',
			ict: 'Instructora de TIC',
			ictDetails: 'Dei aulas sobre habilidades de Tecnologia de Informação e Comunicação: ambiente windows, softwares básicos e uso de internet, ensinando mais de 210 crianças de Educação Primária, de 6 a 12 anos de idade.',
			eru: 'Delegada Internacional de Resposta em Emergências (ERU)',
			eruDetails: 'Trabalhei na Grécia em uma missão temporária (2 meses), propiciando apoio psicossocial para pessoas sírias e outros refugiados e refugiadas chegando à Europa.',
			tj: 'Servidora Pública',
			tjDetails: 'Servidora pública com uma carreira ascendente, começando como técnica administrativa e chegando a ser chefe de setor responsável por projetos sociais.',
			linkedin: 'Para mais informações e referências, por favor visite ',
			brazil: 'Brasil',
			spain: 'Espanha'
		}
	},
	OtherSkills: {
		en: {
			find: "You've found... a computer?!",
			find2: "And it is oddly on",
			investigate: 'Click on the screen to investigate it.',
			languages: 'Languages',
			english: 'English',
			spanish: 'Spanish',
			portuguese: 'Portuguese',
			french: 'French',
			russian: 'Russian',
			fluent: 'Fluent',
			intermediate: 'Intermediate',
			basic: 'Basic',
			other: 'Other skills',
			skill: 'Skill',
			how: 'How I have developed it',
			skill1: 'Working under pressure',
			skill1details: 'More than 5 years as volunteer on ambulances and emergencies',
			skill2: 'Leadership',
			skill2details: 'More than 3 years of professional experience managing different teams',
			skill3: 'Communication',
			skill3details: 'Solid experience teaching, giving formations and speeches',
			skill4: 'Empathy',
			skill4details: 'Psychology formation and humanitarian background',
			skill5: 'Flexibility',
			skill5details: 'Very good experience working within multicultural environments',
			design: 'Graphic design',
			samples: 'Here are samples of some of my design creations:'
		},
		es: {
			find: "Has encontrado... un ordenador?!",
			find2: "Y curiosamente está funcionando...",
			investigate: 'Haz click en la pantalla para investigarlo.',
			languages: 'Idiomas',
			english: 'Inglés',
			spanish: 'Español',
			portuguese: 'Portugués',
			french: 'Francés',
			russian: 'Ruso',
			fluent: 'Fluído',
			intermediate: 'Intermedio',
			basic: 'Básico',
			other: 'Otras competencias',
			skill: 'Competencia',
			how: 'Como la he desarrollado',
			skill1: 'Trabajar bajo presión',
			skill1details: 'Más de 5 años como voluntaria en ambulancias y emergencias',
			skill2: 'Liderazgo',
			skill2details: 'Más de 3 años de experiencia profesional gestionando distintos equipos',
			skill3: 'Comunicación',
			skill3details: 'Sólida experiencia en enseñanza, impartiendo formaciones y charlas',
			skill4: 'Empatía',
			skill4details: 'Formación en psicología y experiencia humanitaria',
			skill5: 'Flexibilidad',
			skill5details: 'Excelente experiencia trabajando en ambientes multiculturales',
			design: 'Diseño gráfico',
			samples: 'Usted puede ver abajo algunos ejemplos de creacciones mías:'
		},
		pt: {
			find: "Você encontrou... um computador?!",
			find2: "E estranhamente está funcionando...",
			investigate: 'Clique na tela para investigá-lo.',
			languages: 'Idiomas',
			english: 'Inglês',
			spanish: 'Espanhol',
			portuguese: 'Português',
			french: 'Francês',
			russian: 'Russo',
			fluent: 'Fluente',
			intermediate: 'Intermediário',
			basic: 'Básico',
			other: 'Outras competências',
			skill: 'Competência',
			how: 'Como eu a desenvolvi',
			skill1: 'Trabalhar sobre pressão',
			skill1details: 'Mais de 5 anos como voluntária em ambulâncias e emergências',
			skill2: 'Liderança',
			skill2details: 'Mais de 3 anos de experiência profissional gestionando diferentes equipes',
			skill3: 'Comunicação',
			skill3details: 'Experiência sólida de ensino, dando formações e palestras',
			skill4: 'Empatia',
			skill4details: 'Formação em psicologia e experiência humanitária',
			skill5: 'Flexibilidade',
			skill5details: 'Excelente experiência trabalhando em ambientes multiculturais',
			design: 'Desenho gráfico',
			samples: 'Abaixo você pode ver alguns exemplos de criações minhas:'
		}
	}
}
